name: Release Node.js App to AWS and Docker Hub

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Or any other version you use

      - name: Install dependencies
        run: |
          npm install

      - name: Set up version tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            abhilinux/express-app:latest
            abhilinux/express-app:${{ env.VERSION }}

      # AWS credentials configuration
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Make sure this is set in your GitHub secrets

      # Initialize Elastic Beanstalk app
      - name: Initialize Elastic Beanstalk app
        run: |
          eb init -p node.js --region ${{ secrets.AWS_REGION }} express-app  # Replace 'my-app-name' with your Elastic Beanstalk app name

      # Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        run: |
          eb deploy  # Deploy the app to Elastic Beanstalk

      # Output deployed URL
      - name: Output deployed URL
        run: |
          echo "Deployed to Elastic Beanstalk at: express-app.us-east-1.elasticbeanstalk.com"  # Replace with your Elastic Beanstalk app URL

